// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZmDsslYlilIJI5k4UGAhIZNOvcYVYS5M',
    appId: '1:555978962711:web:1864c508467a8a2ae9a952',
    messagingSenderId: '555978962711',
    projectId: 'fashion-sketchbook-3f916',
    authDomain: 'fashion-sketchbook-3f916.firebaseapp.com',
    storageBucket: 'fashion-sketchbook-3f916.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaYhZbNKrEwdLLZVSFpE4IfZe3bAVUcJE',
    appId: '1:555978962711:android:dd0ea65379b74cf0e9a952',
    messagingSenderId: '555978962711',
    projectId: 'fashion-sketchbook-3f916',
    storageBucket: 'fashion-sketchbook-3f916.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp7n3stlbs-tFf0Yrx7B90AU8PDzvwDz4',
    appId: '1:555978962711:ios:4e4b9214595537f8e9a952',
    messagingSenderId: '555978962711',
    projectId: 'fashion-sketchbook-3f916',
    storageBucket: 'fashion-sketchbook-3f916.firebasestorage.app',
    iosBundleId: 'com.example.fashionSketchbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp7n3stlbs-tFf0Yrx7B90AU8PDzvwDz4',
    appId: '1:555978962711:ios:4e4b9214595537f8e9a952',
    messagingSenderId: '555978962711',
    projectId: 'fashion-sketchbook-3f916',
    storageBucket: 'fashion-sketchbook-3f916.firebasestorage.app',
    iosBundleId: 'com.example.fashionSketchbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZmDsslYlilIJI5k4UGAhIZNOvcYVYS5M',
    appId: '1:555978962711:web:03cb1f11a351910fe9a952',
    messagingSenderId: '555978962711',
    projectId: 'fashion-sketchbook-3f916',
    authDomain: 'fashion-sketchbook-3f916.firebaseapp.com',
    storageBucket: 'fashion-sketchbook-3f916.firebasestorage.app',
  );
}
