name: fashion_sketchbook
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  signature: ^4.0.0
   

  # Sketching & Drawing Tools
  intl: ^0.20.2
  scribble: ^0.10.0+1

  # Firebase Dependencies (Corrected Versions)
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.7.7
  image_picker: ^1.0.7
  
  # State Management
  provider: ^6.1.2
  flutter_drawing_board: ^0.9.5
  flutter_colorpicker: ^0.4.0

  # Additional UI Dependencies
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/images/sketch_bg.png
    - assets/images/save_icon.png
    - assets/images/clear_icon.png
  uses-material-design: true
